### ISSUE TITLE
Definitions for 'tau_word' and 'lamda'

### ISSUE THREAD

**Issue by n00b001** [Kiode/Text_Watermark_Language_Models#4]
Hello @Kiode ,

I have replicated your code, and it seems to work, but I'd like to know more what is going on.

Can you please give some definitions for the two command line arguments:

- --tau_word
- --lamda

These don't seem to be mentioned in the paper.  
In the code I see them being used, but I'm not quite understand what they are for.

I have seen the parser description, but could you expand upon it?
https://github.com/Kiode/Text_Watermark/blob/86da20fcc8f14506ecb447535100173b12b15e9e/options.py#L11

Thanks!

**Comment by Kiode** [comment]
Hi Alex,

- lamda is the weight used to calculate word-level similarity (see Eq.7 in the paper).
- tau_word is used as the threshold to find the high-quality candidates (see Eq.8 in the paper).

Thanks!
